{{- range .Values.users }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devserver.fullname" $ }}-{{ .name }}
  labels:
    {{- include "devserver.labels" $ | nindent 4 }}
    app: devserver-{{ .name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    {{- include "devserver.selectorLabels" $ | nindent 4 }}
    app: devserver-{{ .name }}
{{- end }}
