{{- range .Values.users }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-public-key
  labels:
    name: {{ .name }}-public-key
data:
  {{ .name }}.pub: |-
    {{ .public_key }}
    {{- range $.Values.master_key }}
    {{ .public_key }}
    {{- end }}
{{- end }}