{{- range .Values.users }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devserver.fullname" $ }}-{{ .name }}
  labels:
    {{- include "devserver.labels" $ | nindent 4 }}
    app: devserver-{{ .name }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "devserver.selectorLabels" $ | nindent 6 }}
      app: devserver-{{ .name }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devserver.selectorLabels" $ | nindent 8 }}
        app: devserver-{{ .name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .serviceAccount }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .name }}-public-key
          configMap:
            name: public-key
            items:
            - key: {{ .name }}.pub
              path: {{ .name }}.pub
        - name: default-files
          configMap:
            name: default-files
      initContainer:
        - name: init-public-key
          image: busybox:latest
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              /var/default_files/init-{{ .name }}.sh
          volumeMounts:
            - name: {{ .name }}-public-key
              mountPath: /var/keys/{{ .name }}.pub
            - name: default-files
              mounthPath: /var/default_files/
              defaultMode: 0777
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}