{{- range .Values.users }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devserver.pvcName" (dict "root" $ "user" .) }}
spec: 
  accessModes:
    {{- if eq $.Values.persistence.type "efs" }}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  storageClassName: {{ include "devserver.storageClassName" $ }}
  resources: 
    requests:
      storage: {{ include "devserver.storageRequest" (dict "root" $ "user" .) }}
---
{{- end }}
